package io.bit3.mgpm.worker;

public enum Action {
  ABORT,
  CLONE_REPOSITORY,
  STASH,
  UPDATE_REMOTE_URL, UNSTASH, PARSE_LOCAL_BRANCHES, PARSE_REMOTE_BRANCHES, DETERMINE_UPSTREAMS, FETCH_REMOTES, CHECKOUT, REBASE, REBASE_ABORT, MERGE, MERGE_ABORT, RESTORE_HEAD, UPDATE_SUBMODULES, EXCEPTION_OCCURRED
}
